//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkPlanner.Resources.AppResources.ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        internal static string LoginField {
            get {
                return ResourceManager.GetString("LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в аккаунт.
        /// </summary>
        internal static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string PasswordField {
            get {
                return ResourceManager.GetString("PasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пароль.
        /// </summary>
        internal static string ShouldShowPassword {
            get {
                return ResourceManager.GetString("ShouldShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string SubmitLoginButton {
            get {
                return ResourceManager.GetString("SubmitLoginButton", resourceCulture);
            }
        }
    }
}
