//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkPlanner.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action completed.
        /// </summary>
        internal static string ActionCompleted {
            get {
                return ResourceManager.GetString("ActionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details.
        /// </summary>
        internal static string AdditionalDetails {
            get {
                return ResourceManager.GetString("AdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdministratorRole {
            get {
                return ResourceManager.GetString("AdministratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in this room. Refresh the page and look for it in the list.
        /// </summary>
        internal static string AlreadyRoomMember {
            get {
                return ResourceManager.GetString("AlreadyRoomMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available roles.
        /// </summary>
        internal static string AvailableRoles {
            get {
                return ResourceManager.GetString("AvailableRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role.
        /// </summary>
        internal static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the server, please try again later.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy room id.
        /// </summary>
        internal static string CopyRoomId {
            get {
                return ResourceManager.GetString("CopyRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new room.
        /// </summary>
        internal static string CreateNewRoom {
            get {
                return ResourceManager.GetString("CreateNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the task creator.
        /// </summary>
        internal static string CreatorInformation {
            get {
                return ResourceManager.GetString("CreatorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline date.
        /// </summary>
        internal static string DeadlineDate {
            get {
                return ResourceManager.GetString("DeadlineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline cannot be less than the current date.
        /// </summary>
        internal static string DeadlineError {
            get {
                return ResourceManager.GetString("DeadlineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline time.
        /// </summary>
        internal static string DeadlineTime {
            get {
                return ResourceManager.GetString("DeadlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete room.
        /// </summary>
        internal static string DeleteRoom {
            get {
                return ResourceManager.GetString("DeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation status.
        /// </summary>
        internal static string EmailConfirmedStatusTitle {
            get {
                return ResourceManager.GetString("EmailConfirmedStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is confirmed.
        /// </summary>
        internal static string EmailIsConfirmedStatus {
            get {
                return ResourceManager.GetString("EmailIsConfirmedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not verified. Would you like to resend a confirmation email again?.
        /// </summary>
        internal static string EmailIsNotConfirmedStatus {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email, please try again later!.
        /// </summary>
        internal static string EmailResentFailed {
            get {
                return ResourceManager.GetString("EmailResentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email was successfully resent. Check your mail.
        /// </summary>
        internal static string EmailResentSuccess {
            get {
                return ResourceManager.GetString("EmailResentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room description.
        /// </summary>
        internal static string EnterRoomDescription {
            get {
                return ResourceManager.GetString("EnterRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room id.
        /// </summary>
        internal static string EnterRoomId {
            get {
                return ResourceManager.GetString("EnterRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter room name.
        /// </summary>
        internal static string EnterRoomName {
            get {
                return ResourceManager.GetString("EnterRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string FailedLoginAlertTitle {
            get {
                return ResourceManager.GetString("FailedLoginAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string FailedRegistrationAlertTitle {
            get {
                return ResourceManager.GetString("FailedRegistrationAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get error!.
        /// </summary>
        internal static string FailedToGetError {
            get {
                return ResourceManager.GetString("FailedToGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        internal static string IncorrectLoginData {
            get {
                return ResourceManager.GetString("IncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect role name.
        /// </summary>
        internal static string IncorrectRoleName {
            get {
                return ResourceManager.GetString("IncorrectRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection, check your connection.
        /// </summary>
        internal static string InternetIsMissing {
            get {
                return ResourceManager.GetString("InternetIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone! Are you sure?.
        /// </summary>
        internal static string IrrevocableAction {
            get {
                return ResourceManager.GetString("IrrevocableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an existing room.
        /// </summary>
        internal static string JoinAnExistingRoom {
            get {
                return ResourceManager.GetString("JoinAnExistingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining an existing room.
        /// </summary>
        internal static string JoiningAnExistingRoom {
            get {
                return ResourceManager.GetString("JoiningAnExistingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string MemberRole {
            get {
                return ResourceManager.GetString("MemberRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, you have no rooms yet, create a room by clicking the plus in the upper right corner..
        /// </summary>
        internal static string NoRooms {
            get {
                return ResourceManager.GetString("NoRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, you have no tasks yet, create a task by clicking the plus in the upper right corner..
        /// </summary>
        internal static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string OwnerRole {
            get {
                return ResourceManager.GetString("OwnerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the password.
        /// </summary>
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        internal static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberUser {
            get {
                return ResourceManager.GetString("RememberUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room description.
        /// </summary>
        internal static string RoomDescription {
            get {
                return ResourceManager.GetString("RoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        internal static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string RoomsPageTitle {
            get {
                return ResourceManager.GetString("RoomsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action.
        /// </summary>
        internal static string SelectAnAction {
            get {
                return ResourceManager.GetString("SelectAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is visible.
        /// </summary>
        internal static string ShouldShowPassword {
            get {
                return ResourceManager.GetString("ShouldShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SubmitLoginButton {
            get {
                return ResourceManager.GetString("SubmitLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string SubmitRegisterButton {
            get {
                return ResourceManager.GetString("SubmitRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered! Now all that remains is to confirm your login email address, check your email address.
        /// </summary>
        internal static string SuccessfulRegistrationAlertMessage {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfull registration.
        /// </summary>
        internal static string SuccessfulRegistrationAlertTitle {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task content.
        /// </summary>
        internal static string TaskContent {
            get {
                return ResourceManager.GetString("TaskContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task name.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is over!.
        /// </summary>
        internal static string TimeEnded {
            get {
                return ResourceManager.GetString("TimeEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of creation.
        /// </summary>
        internal static string TimeOfCreation {
            get {
                return ResourceManager.GetString("TimeOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to end:.
        /// </summary>
        internal static string TimeToEnd {
            get {
                return ResourceManager.GetString("TimeToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update information, please try again later!.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong id!.
        /// </summary>
        internal static string WrongId {
            get {
                return ResourceManager.GetString("WrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your name.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
