//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkPlanner.Resources.AppResources.ru", typeof(AppResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действие выполнено.
        /// </summary>
        internal static string ActionCompleted {
            get {
                return ResourceManager.GetString("ActionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не получилось выполнить действие!.
        /// </summary>
        internal static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные вам комнаты:.
        /// </summary>
        internal static string AvailableRooms {
            get {
                return ResourceManager.GetString("AvailableRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получилось связаться с сервером, попробуйте позже.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спопировать id комнаты.
        /// </summary>
        internal static string CopyRoomId {
            get {
                return ResourceManager.GetString("CopyRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую комнату.
        /// </summary>
        internal static string CreateNewRoom {
            get {
                return ResourceManager.GetString("CreateNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о создателе задачи.
        /// </summary>
        internal static string CreatorInformation {
            get {
                return ResourceManager.GetString("CreatorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок сдачи не может быть меньше текущей даты.
        /// </summary>
        internal static string DeadlineError {
            get {
                return ResourceManager.GetString("DeadlineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайний срок.
        /// </summary>
        internal static string DeadlineTime {
            get {
                return ResourceManager.GetString("DeadlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить комнату.
        /// </summary>
        internal static string DeleteRoom {
            get {
                return ResourceManager.GetString("DeleteRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус подтверждения по электронной почте.
        /// </summary>
        internal static string EmailConfirmedStatusTitle {
            get {
                return ResourceManager.GetString("EmailConfirmedStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты подтвержден.
        /// </summary>
        internal static string EmailIsConfirmedStatus {
            get {
                return ResourceManager.GetString("EmailIsConfirmedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты еще не подтвержден. Хотете получить письмо с подтвержением повторно?.
        /// </summary>
        internal static string EmailIsNotConfirmedStatus {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получилось отправить письмо, попробуйте позже!.
        /// </summary>
        internal static string EmailResentFailed {
            get {
                return ResourceManager.GetString("EmailResentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Письмо успешно переотправлено. Проверьте почту.
        /// </summary>
        internal static string EmailResentSuccess {
            get {
                return ResourceManager.GetString("EmailResentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание комнаты.
        /// </summary>
        internal static string EnterRoomDescription {
            get {
                return ResourceManager.GetString("EnterRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите id комнаты.
        /// </summary>
        internal static string EnterRoomId {
            get {
                return ResourceManager.GetString("EnterRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название комнаты.
        /// </summary>
        internal static string EnterRoomName {
            get {
                return ResourceManager.GetString("EnterRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при входе в аккаунт.
        /// </summary>
        internal static string FailedLoginAlertTitle {
            get {
                return ResourceManager.GetString("FailedLoginAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при регистрации.
        /// </summary>
        internal static string FailedRegistrationAlertTitle {
            get {
                return ResourceManager.GetString("FailedRegistrationAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получилось получить информацию об ошибке!.
        /// </summary>
        internal static string FailedToGetError {
            get {
                return ResourceManager.GetString("FailedToGetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный логин или пароль.
        /// </summary>
        internal static string IncorrectLoginData {
            get {
                return ResourceManager.GetString("IncorrectLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует соединение с интернетом, проверьте свое подключение.
        /// </summary>
        internal static string InternetIsMissing {
            get {
                return ResourceManager.GetString("InternetIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это действие не может быть отменено! Вы уверены?.
        /// </summary>
        internal static string IrrevocableAction {
            get {
                return ResourceManager.GetString("IrrevocableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться к существующей комнате.
        /// </summary>
        internal static string JoinAnExistingRoom {
            get {
                return ResourceManager.GetString("JoinAnExistingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединение к существующей комнате.
        /// </summary>
        internal static string JoiningAnExistingRoom {
            get {
                return ResourceManager.GetString("JoiningAnExistingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в аккаунт.
        /// </summary>
        internal static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        internal static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер телефона.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        internal static string ProfilePageTitle {
            get {
                return ResourceManager.GetString("ProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня.
        /// </summary>
        internal static string RememberUser {
            get {
                return ResourceManager.GetString("RememberUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание комнаты.
        /// </summary>
        internal static string RoomDescription {
            get {
                return ResourceManager.GetString("RoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название комнаты.
        /// </summary>
        internal static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комнаты.
        /// </summary>
        internal static string RoomsPageTitle {
            get {
                return ResourceManager.GetString("RoomsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string SelectAnAction {
            get {
                return ResourceManager.GetString("SelectAnAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пароль.
        /// </summary>
        internal static string ShouldShowPassword {
            get {
                return ResourceManager.GetString("ShouldShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string SubmitLoginButton {
            get {
                return ResourceManager.GetString("SubmitLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегестрироваться.
        /// </summary>
        internal static string SubmitRegisterButton {
            get {
                return ResourceManager.GetString("SubmitRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегестрировались! Теперь осталось подтвердить адрес электронной почты для входа, проверьте адрес электронной почты..
        /// </summary>
        internal static string SuccessfulRegistrationAlertMessage {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная регистрация.
        /// </summary>
        internal static string SuccessfulRegistrationAlertTitle {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время вышло!.
        /// </summary>
        internal static string TimeEnded {
            get {
                return ResourceManager.GetString("TimeEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания.
        /// </summary>
        internal static string TimeOfCreation {
            get {
                return ResourceManager.GetString("TimeOfCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время до конца:.
        /// </summary>
        internal static string TimeToEnd {
            get {
                return ResourceManager.GetString("TimeToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не получилось обновить информацию, попробуйте обновить попозже!.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить описание комнаты.
        /// </summary>
        internal static string UpdateRoom {
            get {
                return ResourceManager.GetString("UpdateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный id!.
        /// </summary>
        internal static string WrongId {
            get {
                return ResourceManager.GetString("WrongId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как вас зовут.
        /// </summary>
        internal static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль.
        /// </summary>
        internal static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
